In [2]:
import pandas as pd 
df= pd.read_csv("weather2.csv")    
df

,MinTemp,MaxTemp,Rainfall,Evaporation,Sunshine,WindGustDir,WindGustSpeed,WindDir9am,WindDir3pm,WindSpeed9am,WindSpeed3pm,Humidity9am,Humidity3pm,Pressure9am
0,8.0,24.3,0.0,3.4,6.3,NW,30,SW,NW,6,20,68,29,1019.7
1,14.0,26.9,3.6,4.4,9.7,ENE,39,E,W,4,17,80,36,1012.4
2,13.7,23.4,3.6,5.8,3.3,NW,85,N,NNE,6,6,82,69,1009.5
3,13.3,15.5,39.8,7.2,9.1,NW,54,WNW,W,30,24,62,56,1005.5
4,7.6,16.1,2.8,5.6,10.6,SSE,50,SSE,ESE,20,28,68,49,1018.3
5,6.2,16.9,0.0,5.8,8.2,SE,44,SE,E,20,24,70,57,1023.8
6,6.1,18.2,0.2,4.2,8.4,SE,43,SE,ESE,19,26,63,47,1024.6
7,8.3,17.0,0.0,5.6,4.6,E,41,SE,E,11,24,65,57,1026.2
8,8.8,19.5,0.0,4.0,4.1,S,48,E,ENE,19,17,70,48,1026.1
9,8.4,22.8,16.2,5.4,7.7,E,31,S,ESE,7,6,82,32,1024.1
10,9.1,25.2,0.0,4.2,11.9,N,30,SE,NW,6,9,74,34,1024.4
11,8.5,27.3,0.2,7.2,12.5,E,41,E,NW,2,15,54,35,1023.8
12,10.1,27.9,0.0,7.2,13.0,WNW,30,S,NW,6,7,62,29,1022.0
13,12.1,30.9,0.0,6.2,12.4,NW,44,WNW,W,7,20,67,20,1017.3
14,10.1,31.2,0.0,8.8,13.1,NW,41,S,W,6,20,45,16,1018.2
15,12.4,32.1,0.0,8.4,11.1,E,46,SE,WSW,7,9,70,22,1017.9
16,13.8,31.2,0.0,7.2,8.4,ESE,44,WSW,W,6,19,72,23,1014.4
17,11.7,30.0,1.2,7.2,10.1,S,52,SW,NE,6,11,59,26,1016.4
18,12.4,32.3,0.6,7.4,13.0,E,39,NNE,W,4,17,60,25,1017.1
19,15.6,33.4,0.0,8.0,10.4,NE,33,NNW,NNW,2,13,61,27,1018.5
20,15.3,33.4,0.0,8.8,9.5,WNW,59,N,NW,2,31,60,26,1012.4
21,16.4,19.4,0.4,9.2,0.0,E,26,ENE,E,6,11,88,72,1010.7
22,12.8,18.5,25.8,2.8,0.6,ESE,28,S,SE,13,13,91,79,1014.0

In [11]:
df = pd.read_excel("weather2.xlsx")
df

ValueError: Excel file format cannot be determined, you must specify an engine manually.

In [19]:
weather_data = {
    'day':['1/1/2019','1/2/2019','1/3/2017'],
    'windspeed':[23,43,12],
    'event':['rain','snow','hot']  
}
df = pd.DataFrame(weather_data)
df

        day  windspeed event
0  1/1/2019         23  rain
1  1/2/2019         43  snow
2  1/3/2017         12   hot

In [17]:
weather_d = [
    ('1/2/2019',32,43,'rain'),
    ('2/3/2012',32,12,'snow')
]
df=pd.DataFrame(weather_data,columns = ["day","temperature","windsped","event"])
df

        day temperature windsped event
0  1/1/2019         NaN      NaN  rain
1  1/2/2019         NaN      NaN  snow
2  1/3/2017         NaN      NaN   hot